package GUI;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Ulises Tovar
 */
public class PanelVictoria extends javax.swing.JPanel {

    /**
     * Creates new form PanelVictoria
     */
    public PanelVictoria() {
        initComponents();
        this.setBackground( new Color(0, 0, 0, 160) );
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        grphcs.setColor(getBackground());
        grphcs.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        labelMensajeDeVictoria1 = new javax.swing.JLabel();
        labelTiempo1 = new javax.swing.JLabel();
        labelNombreGanador = new javax.swing.JLabel();
        iconoFinRonda = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelMensajeDeVictoria1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        labelMensajeDeVictoria1.setForeground(new java.awt.Color(255, 153, 0));
        labelMensajeDeVictoria1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensajeDeVictoria1.setText("La victoria de esta ronda es para:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel1.add(labelMensajeDeVictoria1, gridBagConstraints);

        labelTiempo1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        labelTiempo1.setForeground(new java.awt.Color(153, 0, 204));
        labelTiempo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTiempo1.setText("Próxima ronda: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(labelTiempo1, gridBagConstraints);

        labelNombreGanador.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        labelNombreGanador.setForeground(new java.awt.Color(153, 0, 204));
        labelNombreGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreGanador.setText("[Nombre del ganador]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(labelNombreGanador, gridBagConstraints);

        iconoFinRonda.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        iconoFinRonda.setForeground(new java.awt.Color(255, 153, 0));
        iconoFinRonda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoFinRonda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AnuncioFinDeRonda.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel1.add(iconoFinRonda, gridBagConstraints);

        labelTiempo.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        labelTiempo.setForeground(new java.awt.Color(153, 0, 204));
        labelTiempo.setText("[Tiempo]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(labelTiempo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel iconoFinRonda;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelMensajeDeVictoria1;
    public javax.swing.JLabel labelNombreGanador;
    public javax.swing.JLabel labelTiempo;
    public javax.swing.JLabel labelTiempo1;
    // End of variables declaration//GEN-END:variables
}
