/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JLabel;
import piezazgraficas.TarjetaGrafica;

/**
 *
 * @author Ulises Tovar
 */
public class PanelDeJugador extends javax.swing.JPanel {

    /**
     * Creates new form PanelDeJugador
     */
    public PanelDeJugador() {
        initComponents();
    }

    public JLabel getLabelCombos() {
        return labelCombos;
    }

    public JLabel getLabelDinero() {
        return labelDinero;
    }

    public JLabel getLabelMarcadas() {
        return labelMarcadas;
    }

    public JLabel getLabelNombre() {
        return labelNombre;
    }

    public TarjetaGrafica getTarjetaGrafica1() {
        return tarjetaGrafica1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelControl = new javax.swing.JPanel();
        panelCombos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelCombos = new javax.swing.JLabel();
        panelDinero = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelDinero = new javax.swing.JLabel();
        panelCartasMarcadas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelMarcadas = new javax.swing.JLabel();
        panelJugador = new javax.swing.JPanel();
        tarjetaGrafica1 = new piezazgraficas.TarjetaGrafica();
        labelNombre = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        panelControl.setLayout(new java.awt.GridBagLayout());

        panelCombos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCombos.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Combos");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCombos.add(jLabel6, java.awt.BorderLayout.NORTH);

        labelCombos.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelCombos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCombos.setText("0");
        panelCombos.add(labelCombos, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelControl.add(panelCombos, gridBagConstraints);

        panelDinero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDinero.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dinero");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDinero.add(jLabel4, java.awt.BorderLayout.NORTH);

        labelDinero.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelDinero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDinero.setText("$0");
        panelDinero.add(labelDinero, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelControl.add(panelDinero, gridBagConstraints);

        panelCartasMarcadas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCartasMarcadas.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cartas Marcadas");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCartasMarcadas.add(jLabel2, java.awt.BorderLayout.NORTH);

        labelMarcadas.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelMarcadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMarcadas.setText("0");
        panelCartasMarcadas.add(labelMarcadas, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelControl.add(panelCartasMarcadas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(panelControl, gridBagConstraints);

        panelJugador.setLayout(new java.awt.BorderLayout());
        panelJugador.add(tarjetaGrafica1, java.awt.BorderLayout.CENTER);

        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombre");
        labelNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelJugador.add(labelNombre, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panelJugador, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelCombos;
    private javax.swing.JLabel labelDinero;
    private javax.swing.JLabel labelMarcadas;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JPanel panelCartasMarcadas;
    private javax.swing.JPanel panelCombos;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelDinero;
    private javax.swing.JPanel panelJugador;
    private piezazgraficas.TarjetaGrafica tarjetaGrafica1;
    // End of variables declaration//GEN-END:variables
}
