/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Ulises Tovar
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form TableroV2
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLayeredPane = new javax.swing.JLayeredPane();
        panelPrincipal = new javax.swing.JPanel();
        panelGriton = new javax.swing.JPanel();
        labelNombreCarta = new javax.swing.JLabel();
        panelCarta = new javax.swing.JPanel();
        barraDeProgreso = new javax.swing.JProgressBar();
        cartaGrafica_Griton = new piezazgraficas.CartaGrafica();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcionCarta = new javax.swing.JTextArea();
        panelJugador = new javax.swing.JPanel();
        tarjetaGrafica1 = new piezazgraficas.TarjetaGrafica();
        labelNombre = new javax.swing.JLabel();
        panelControl = new javax.swing.JPanel();
        botonLoteria = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelCombos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelCombos = new javax.swing.JLabel();
        panelDinero = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelDinero = new javax.swing.JLabel();
        panelCartasMarcadas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelMarcadas = new javax.swing.JLabel();
        panelRondas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelRonda = new javax.swing.JLabel();
        panelOtrosJugadores = new javax.swing.JPanel();
        panelSelector = new javax.swing.JPanel();
        botonNavOtros_Izq = new javax.swing.JButton();
        botonNavOtros_Der = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panelCard_Selector = new javax.swing.JPanel();
        panelOtros = new javax.swing.JPanel();
        botonOtro_1 = new javax.swing.JButton();
        botonOtro_2 = new javax.swing.JButton();
        botonOtro_3 = new javax.swing.JButton();
        botonOtro_4 = new javax.swing.JButton();
        panelEstadisticas_Otro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelCartasMarcadas_Otro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelMarcadas_Otro = new javax.swing.JLabel();
        panelCombos_Otro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        labelCombos_Otro = new javax.swing.JLabel();
        panelDinero_Otro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelDinero_Otro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(750, 550));

        jLayeredPane.setLayout(new javax.swing.OverlayLayout(jLayeredPane));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelGriton.setLayout(new java.awt.GridBagLayout());

        labelNombreCarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreCarta.setText("Nombre de la carta");
        labelNombreCarta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelGriton.add(labelNombreCarta, gridBagConstraints);

        panelCarta.setBackground(new java.awt.Color(204, 204, 255));
        panelCarta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCarta.setLayout(new java.awt.BorderLayout());
        panelCarta.add(barraDeProgreso, java.awt.BorderLayout.SOUTH);
        panelCarta.add(cartaGrafica_Griton, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelGriton.add(panelCarta, gridBagConstraints);

        textAreaDescripcionCarta.setEditable(false);
        textAreaDescripcionCarta.setColumns(20);
        textAreaDescripcionCarta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textAreaDescripcionCarta.setLineWrap(true);
        textAreaDescripcionCarta.setRows(2);
        textAreaDescripcionCarta.setOpaque(false);
        jScrollPane1.setViewportView(textAreaDescripcionCarta);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelGriton.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelGriton, gridBagConstraints);

        panelJugador.setLayout(new java.awt.BorderLayout());
        panelJugador.add(tarjetaGrafica1, java.awt.BorderLayout.CENTER);

        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombre");
        labelNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelJugador.add(labelNombre, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelJugador, gridBagConstraints);

        panelControl.setLayout(new java.awt.GridBagLayout());

        botonLoteria.setBackground(new java.awt.Color(204, 204, 0));
        botonLoteria.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        botonLoteria.setText("¡Lotería!");
        botonLoteria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLoteria.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelControl.add(botonLoteria, gridBagConstraints);

        jLabel9.setText("Tu información:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelControl.add(jLabel9, gridBagConstraints);

        panelCombos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCombos.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Combos");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCombos.add(jLabel6, java.awt.BorderLayout.NORTH);

        labelCombos.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelCombos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCombos.setText("0");
        panelCombos.add(labelCombos, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelControl.add(panelCombos, gridBagConstraints);

        panelDinero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDinero.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dinero");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDinero.add(jLabel4, java.awt.BorderLayout.NORTH);

        labelDinero.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelDinero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDinero.setText("$0");
        panelDinero.add(labelDinero, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelControl.add(panelDinero, gridBagConstraints);

        panelCartasMarcadas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCartasMarcadas.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cartas Marcadas");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCartasMarcadas.add(jLabel2, java.awt.BorderLayout.NORTH);

        labelMarcadas.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelMarcadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMarcadas.setText("0");
        panelCartasMarcadas.add(labelMarcadas, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelControl.add(panelCartasMarcadas, gridBagConstraints);

        panelRondas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelRondas.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ronda");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelRondas.add(jLabel8, java.awt.BorderLayout.NORTH);

        labelRonda.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelRonda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRonda.setText("0");
        panelRondas.add(labelRonda, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelControl.add(panelRondas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelControl, gridBagConstraints);

        panelOtrosJugadores.setLayout(new javax.swing.BoxLayout(panelOtrosJugadores, javax.swing.BoxLayout.LINE_AXIS));

        panelSelector.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSelector.setLayout(new java.awt.GridBagLayout());

        botonNavOtros_Izq.setText("<");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelSelector.add(botonNavOtros_Izq, gridBagConstraints);

        botonNavOtros_Der.setText(">");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        panelSelector.add(botonNavOtros_Der, gridBagConstraints);

        jLabel10.setText("1/1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        panelSelector.add(jLabel10, gridBagConstraints);

        panelCard_Selector.setLayout(new java.awt.CardLayout());

        panelOtros.setLayout(new java.awt.GridLayout(2, 2));

        botonOtro_1.setBackground(new java.awt.Color(102, 102, 255));
        botonOtro_1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonOtro_1.setForeground(new java.awt.Color(255, 255, 255));
        botonOtro_1.setText("Nombre 1");
        botonOtro_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOtro_1.setFocusable(false);
        panelOtros.add(botonOtro_1);

        botonOtro_2.setBackground(new java.awt.Color(255, 51, 51));
        botonOtro_2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonOtro_2.setForeground(new java.awt.Color(255, 255, 255));
        botonOtro_2.setText("Nombre 2");
        botonOtro_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOtro_2.setFocusable(false);
        panelOtros.add(botonOtro_2);

        botonOtro_3.setBackground(new java.awt.Color(51, 204, 0));
        botonOtro_3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonOtro_3.setForeground(new java.awt.Color(255, 255, 255));
        botonOtro_3.setText("Nombre 3");
        botonOtro_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOtro_3.setFocusable(false);
        panelOtros.add(botonOtro_3);

        botonOtro_4.setBackground(new java.awt.Color(204, 0, 204));
        botonOtro_4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonOtro_4.setForeground(new java.awt.Color(255, 255, 255));
        botonOtro_4.setText("Nombre 4");
        botonOtro_4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOtro_4.setFocusable(false);
        panelOtros.add(botonOtro_4);

        panelCard_Selector.add(panelOtros, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelSelector.add(panelCard_Selector, gridBagConstraints);

        panelOtrosJugadores.add(panelSelector);

        panelEstadisticas_Otro.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre de otro jugador");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelEstadisticas_Otro.add(jLabel7, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        panelCartasMarcadas_Otro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCartasMarcadas_Otro.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cartas Marcadas");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCartasMarcadas_Otro.add(jLabel1, java.awt.BorderLayout.NORTH);

        labelMarcadas_Otro.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelMarcadas_Otro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMarcadas_Otro.setText("0");
        panelCartasMarcadas_Otro.add(labelMarcadas_Otro, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelCartasMarcadas_Otro);

        panelCombos_Otro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCombos_Otro.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Combos");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCombos_Otro.add(jLabel5, java.awt.BorderLayout.NORTH);

        labelCombos_Otro.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelCombos_Otro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCombos_Otro.setText("0");
        panelCombos_Otro.add(labelCombos_Otro, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelCombos_Otro);

        panelDinero_Otro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDinero_Otro.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dinero");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDinero_Otro.add(jLabel3, java.awt.BorderLayout.NORTH);

        labelDinero_Otro.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelDinero_Otro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDinero_Otro.setText("$0");
        panelDinero_Otro.add(labelDinero_Otro, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelDinero_Otro);

        panelEstadisticas_Otro.add(jPanel1, java.awt.BorderLayout.CENTER);

        panelOtrosJugadores.add(panelEstadisticas_Otro);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.25;
        panelPrincipal.add(panelOtrosJugadores, gridBagConstraints);

        jLayeredPane.add(panelPrincipal);

        getContentPane().add(jLayeredPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar barraDeProgreso;
    public javax.swing.JButton botonLoteria;
    public javax.swing.JButton botonNavOtros_Der;
    public javax.swing.JButton botonNavOtros_Izq;
    public javax.swing.JButton botonOtro_1;
    public javax.swing.JButton botonOtro_2;
    public javax.swing.JButton botonOtro_3;
    public javax.swing.JButton botonOtro_4;
    public piezazgraficas.CartaGrafica cartaGrafica_Griton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLayeredPane jLayeredPane;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelCombos;
    public javax.swing.JLabel labelCombos_Otro;
    public javax.swing.JLabel labelDinero;
    public javax.swing.JLabel labelDinero_Otro;
    public javax.swing.JLabel labelMarcadas;
    public javax.swing.JLabel labelMarcadas_Otro;
    public javax.swing.JLabel labelNombre;
    public javax.swing.JLabel labelNombreCarta;
    public javax.swing.JLabel labelRonda;
    public javax.swing.JPanel panelCard_Selector;
    public javax.swing.JPanel panelCarta;
    public javax.swing.JPanel panelCartasMarcadas;
    public javax.swing.JPanel panelCartasMarcadas_Otro;
    public javax.swing.JPanel panelCombos;
    public javax.swing.JPanel panelCombos_Otro;
    public javax.swing.JPanel panelControl;
    public javax.swing.JPanel panelDinero;
    public javax.swing.JPanel panelDinero_Otro;
    public javax.swing.JPanel panelEstadisticas_Otro;
    public javax.swing.JPanel panelGriton;
    public javax.swing.JPanel panelJugador;
    public javax.swing.JPanel panelOtros;
    public javax.swing.JPanel panelOtrosJugadores;
    public javax.swing.JPanel panelPrincipal;
    public javax.swing.JPanel panelRondas;
    public javax.swing.JPanel panelSelector;
    public piezazgraficas.TarjetaGrafica tarjetaGrafica1;
    public javax.swing.JTextArea textAreaDescripcionCarta;
    // End of variables declaration//GEN-END:variables
}
