package GUI;

import piezazgraficas.TarjetaGrafica_Old;
import piezazgraficas.GlassPane;
import piezazgraficas.ImagenesDeCartas;
import piezazgraficas.CartaGrafica;
import PiezasDeLoteria.Carta;
import PiezasDeLoteria.Jugador;
import PiezasDeLoteria.ListaDeCartas;
import PiezasDeLoteria.Nombres;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;

/**
 *
 * @author Lenovo ThinkPad T430
 */
public class Tablero_Old extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero_Old() {
        initComponents();

        ajustarCartaGriton();
        //añadirListenersTarjeta();
        ajustarGlassPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIzquierdo = new javax.swing.JPanel();
        panelGriton = new javax.swing.JPanel();
        panelCartaGriton = new javax.swing.JPanel();
        descripcionCartaGriton = new javax.swing.JLabel();
        nombreCartaLanzada = new javax.swing.JLabel();
        panelSubTarjeta = new javax.swing.JPanel();
        nombreSubTarjeta = new javax.swing.JLabel();
        subTarjeta = new piezazgraficas.TarjetaGrafica_Old();
        panelDeOpciones = new javax.swing.JPanel();
        nombrePanelDeOpciones = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        botonSigTarjeta = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        botonAntTarjeta = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        botonMostrarTarjeta = new javax.swing.JToggleButton();
        panelTarjetaPrincipal = new javax.swing.JPanel();
        tarjetaPrincipal = new piezazgraficas.TarjetaGrafica_Old();
        nombreTarjetaPrincipal = new javax.swing.JLabel();
        panelDeControl = new javax.swing.JPanel();
        numeroDeRonda = new javax.swing.JLabel();
        numeroDeCartasMarcadas = new javax.swing.JLabel();
        numeroDeJugadores = new javax.swing.JLabel();
        botonLoteria = new javax.swing.JButton();
        panelInfoOtrosJugadores = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelIzquierdo.setLayout(new java.awt.BorderLayout());

        panelCartaGriton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout panelCartaGritonLayout = new javax.swing.GroupLayout(panelCartaGriton);
        panelCartaGriton.setLayout(panelCartaGritonLayout);
        panelCartaGritonLayout.setHorizontalGroup(
            panelCartaGritonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        panelCartaGritonLayout.setVerticalGroup(
            panelCartaGritonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        descripcionCartaGriton.setText("Descripción");
        descripcionCartaGriton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        descripcionCartaGriton.setBorder(new javax.swing.border.MatteBorder(null));

        nombreCartaLanzada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCartaLanzada.setText("Carta lanzada");
        nombreCartaLanzada.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelGritonLayout = new javax.swing.GroupLayout(panelGriton);
        panelGriton.setLayout(panelGritonLayout);
        panelGritonLayout.setHorizontalGroup(
            panelGritonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGritonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGritonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(descripcionCartaGriton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCartaGriton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCartaLanzada, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGritonLayout.setVerticalGroup(
            panelGritonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGritonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreCartaLanzada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCartaGriton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descripcionCartaGriton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelIzquierdo.add(panelGriton, java.awt.BorderLayout.NORTH);

        nombreSubTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreSubTarjeta.setText("Carta de otro jugador");
        nombreSubTarjeta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        panelDeOpciones.setLayout(new javax.swing.BoxLayout(panelDeOpciones, javax.swing.BoxLayout.Y_AXIS));

        nombrePanelDeOpciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrePanelDeOpciones.setText("Opciones");
        nombrePanelDeOpciones.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        panelDeOpciones.add(nombrePanelDeOpciones);
        panelDeOpciones.add(filler3);

        botonSigTarjeta.setText("Siguiente");
        panelDeOpciones.add(botonSigTarjeta);
        panelDeOpciones.add(filler1);

        botonAntTarjeta.setText("Anterior");
        panelDeOpciones.add(botonAntTarjeta);
        panelDeOpciones.add(filler2);

        botonMostrarTarjeta.setText("Mostrar");
        panelDeOpciones.add(botonMostrarTarjeta);

        javax.swing.GroupLayout panelSubTarjetaLayout = new javax.swing.GroupLayout(panelSubTarjeta);
        panelSubTarjeta.setLayout(panelSubTarjetaLayout);
        panelSubTarjetaLayout.setHorizontalGroup(
            panelSubTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubTarjetaLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(panelSubTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nombreSubTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDeOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelSubTarjetaLayout.setVerticalGroup(
            panelSubTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubTarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreSubTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSubTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSubTarjetaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(panelDeOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelIzquierdo.add(panelSubTarjeta, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelIzquierdo, java.awt.BorderLayout.WEST);

        nombreTarjetaPrincipal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nombreTarjetaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreTarjetaPrincipal.setText("Nombre del jugador");

        javax.swing.GroupLayout panelTarjetaPrincipalLayout = new javax.swing.GroupLayout(panelTarjetaPrincipal);
        panelTarjetaPrincipal.setLayout(panelTarjetaPrincipalLayout);
        panelTarjetaPrincipalLayout.setHorizontalGroup(
            panelTarjetaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTarjetaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tarjetaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTarjetaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelTarjetaPrincipalLayout.setVerticalGroup(
            panelTarjetaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreTarjetaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarjetaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelTarjetaPrincipal, java.awt.BorderLayout.CENTER);

        panelDeControl.setLayout(new java.awt.BorderLayout());

        numeroDeRonda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numeroDeRonda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDeRonda.setText("Ronda: [número]");
        panelDeControl.add(numeroDeRonda, java.awt.BorderLayout.NORTH);

        numeroDeCartasMarcadas.setText("Cartas marcadas: [número]");
        panelDeControl.add(numeroDeCartasMarcadas, java.awt.BorderLayout.WEST);

        numeroDeJugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDeJugadores.setText("Número de jugadores: [número]");
        panelDeControl.add(numeroDeJugadores, java.awt.BorderLayout.CENTER);

        botonLoteria.setText("¡Lotería!");
        panelDeControl.add(botonLoteria, java.awt.BorderLayout.EAST);

        panelInfoOtrosJugadores.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));
        panelDeControl.add(panelInfoOtrosJugadores, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelDeControl, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero_Old().setVisible(true);
            }
        });
    }

    public void setTarjetaPrincipal(Jugador jugador) {
        tarjetaPrincipal.setTarjeta(jugador.getTarjeta());
        nombreTarjetaPrincipal.setText(jugador.getNombre());
        tarjetaPrincipal.actualizar();
    }

    public void setSubTarjeta(Jugador jugador) {
        subTarjeta.setTarjeta(jugador.getTarjeta());
        nombreSubTarjeta.setText(jugador.getNombre());

        int posicion = 0;
        for (CartaGrafica cartaGrafica : subTarjeta.getCartasGraficas()) {
            cartaGrafica.setMarcada(false);
            for (Integer posicionMarcada : jugador.getTarjeta().getPosicionesMarcadas()) {
                if (posicion == posicionMarcada) {
                    cartaGrafica.setMarcada(true);
                }
            }
            posicion++;
        }

//        for (Integer posicionMarcada : jugador.getTarjeta().getPosicionesMarcadas()) {
//            subTarjeta.marcarCarta(posicionMarcada, true);
//        }
        subTarjeta.actualizar();

    }

    public void setCartaGriton(Carta carta) {
        cartaGriton.setImagenDir(ImagenesDeCartas.asignarImagen(carta.getId()));
        cartaGriton.ajustar();
        descripcionCartaGriton.setText("<html>\t" + carta.getDescripcion() + "<html>\t");

    }

    private void ajustarCartaGriton() {
        cartaGriton = new CartaGrafica(Nombres.ElGallo);
        cartaGriton.setSize(panelCartaGriton.getSize());
        cartaGriton.ajustar();

        panelCartaGriton.add(cartaGriton);

        panelCartaGriton.repaint();
    }

    public JButton getBotonAntTarjeta() {
        return botonAntTarjeta;
    }

    public JToggleButton getBotonMostrarTarjeta() {
        return botonMostrarTarjeta;
    }

    public JButton getBotonSigTarjeta() {
        return botonSigTarjeta;
    }

//    private void añadirListenersTarjeta() {
//        //Añadir eventos
//        ArrayList<CartaGrafica> cartasGraficas = tarjetaPrincipal.getCartasGraficas();
//        for (CartaGrafica cartaGrafica : cartasGraficas) {
//            cartaGrafica.addMouseListener(new MouseAdapter() {
//                @Override
//                public void mouseClicked(MouseEvent e) {
//                    int posicionActual = cartasGraficas.indexOf(cartaGrafica);
//
//                    if (!cartaGrafica.isMarcada()) {
//                        tarjetaPrincipal.marcarCarta(posicionActual, true);
//                        tarjetaPrincipal.getTarjeta().marcarCarta(posicionActual);
//                    } else {
//                        tarjetaPrincipal.marcarCarta(posicionActual, false);
//                        tarjetaPrincipal.getTarjeta().desmarcarCarta(posicionActual);
//                    }
//
//                    numeroDeCartasMarcadas.setText("Cartas marcadas: " + tarjetaPrincipal.getTarjeta().getCantidadDeCartasMarcadas());
//                }
//            });
//        }
//    }
    public TarjetaGrafica_Old getTarjetaPrincipal() {
        return tarjetaPrincipal;
    }

    public void setMarcadorRonda(int numero) {
        numeroDeRonda.setText("Ronda: " + numero);
    }

    public void terminar() {
        glassPane.setVisible(true);
    }

    public JButton getBotonLoteria() {
        return botonLoteria;
    }

    private void ajustarGlassPane() {
        glassPane = new GlassPane();
        glassPane.setSize(this.getSize());
        ImageIcon ii = new ImageIcon("src\\imagenes\\AnuncioFinDeRonda.png");
        glassPane.setIcono(ii);

        setGlassPane(glassPane);
    }

    public void setMarcadorNumeroDeJugadores(int cantidad) {
        numeroDeJugadores.setText("Número de jugadores: " + cantidad);
    }

    public JPanel getPanelInfoOtrosJugadores() {
        return panelInfoOtrosJugadores;
    }

    public void setInformacionJugadores(ArrayList<JTextArea> informacionJugadores) {
        this.informacionJugadores = informacionJugadores;
    }

    public ArrayList<JTextArea> getInformacionJugadores() {
        return informacionJugadores;
    }

    public void setMarcadorNumeroCartasMarcadas(int cantidad) {
        numeroDeCartasMarcadas.setText("Cartas marcadas tuyas: " + cantidad);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAntTarjeta;
    private javax.swing.JButton botonLoteria;
    private javax.swing.JToggleButton botonMostrarTarjeta;
    private javax.swing.JButton botonSigTarjeta;
    private javax.swing.JLabel descripcionCartaGriton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel nombreCartaLanzada;
    private javax.swing.JLabel nombrePanelDeOpciones;
    private javax.swing.JLabel nombreSubTarjeta;
    private javax.swing.JLabel nombreTarjetaPrincipal;
    private javax.swing.JLabel numeroDeCartasMarcadas;
    private javax.swing.JLabel numeroDeJugadores;
    private javax.swing.JLabel numeroDeRonda;
    private javax.swing.JPanel panelCartaGriton;
    private javax.swing.JPanel panelDeControl;
    private javax.swing.JPanel panelDeOpciones;
    private javax.swing.JPanel panelGriton;
    private javax.swing.JPanel panelInfoOtrosJugadores;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelSubTarjeta;
    private javax.swing.JPanel panelTarjetaPrincipal;
    private piezazgraficas.TarjetaGrafica_Old subTarjeta;
    private piezazgraficas.TarjetaGrafica_Old tarjetaPrincipal;
    // End of variables declaration//GEN-END:variables

    private CartaGrafica cartaGriton;
    private GlassPane glassPane;
    private ArrayList<JTextArea> informacionJugadores;
}
