/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import PiezasDeLoteria.Jugador;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo ThinkPad T430
 */
public class IngresarNombre extends PanelDeMenu {

    private final Jugador jugador;
    private final String mensajeAdvertencia = "Este campo no puede estar vacío";

    /**
     * Creates new form ingresarNombre
     *
     * @param jugador
     */
    public IngresarNombre(Jugador jugador) {
        initComponents();
        this.jugador = jugador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        texttFieldNombre = new javax.swing.JTextField();
        labelAdvertencia = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresa tu nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        add(jLabel1, gridBagConstraints);

        texttFieldNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        texttFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        texttFieldNombre.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(texttFieldNombre, gridBagConstraints);

        labelAdvertencia.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(labelAdvertencia, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAdvertencia;
    private javax.swing.JTextField texttFieldNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean ejecutar() {
        if (!texttFieldNombre.getText().equals("")) {
            jugador.setNombre(texttFieldNombre.getText());
            return true;
        } else {
            labelAdvertencia.setText(mensajeAdvertencia);
            return false;
        }
    }

}
