/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.CardLayout;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Lenovo ThinkPad T430
 */
public class MenuInicio extends javax.swing.JFrame {

    private final ArrayList<PanelDeMenu> menus;
    private int posicionMostrandose;
    private boolean terminado;
    private final String marco = "src\\imagenes\\marco.png";

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
        ajustarMarco();
        menus = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imagenInicio = new javax.swing.JLabel();
        cartaGrafica1 = new piezazgraficas.CartaGrafica();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        opciones = new javax.swing.JPanel();
        botonesDeControl = new javax.swing.JPanel();
        botonOK = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(643, 760));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        imagenInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/japan landscape.jpg"))); // NOI18N
        imagenInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = -200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(imagenInicio, gridBagConstraints);

        cartaGrafica1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(cartaGrafica1, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setMaximumSize(getMinimumSize());
        jPanel1.setMinimumSize(new java.awt.Dimension(660, 635));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        opciones.setBackground(new java.awt.Color(255, 255, 255));
        opciones.setOpaque(false);
        opciones.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(opciones, gridBagConstraints);

        botonesDeControl.setOpaque(false);
        botonesDeControl.setLayout(new java.awt.GridBagLayout());

        botonOK.setBackground(new java.awt.Color(255, 0, 0));
        botonOK.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonOK.setForeground(new java.awt.Color(255, 255, 255));
        botonOK.setText("OK");
        botonOK.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        botonesDeControl.add(botonOK, gridBagConstraints);

        botonAtras.setBackground(new java.awt.Color(255, 0, 0));
        botonAtras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(255, 255, 255));
        botonAtras.setText("Atrás");
        botonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        botonesDeControl.add(botonAtras, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        jPanel2.add(botonesDeControl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(45, 50, 45, 50);
        jPanel1.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        PanelDeMenu panel = menus.get(posicionMostrandose);
        boolean sePudoEjecutar = panel.ejecutar();
        if (sePudoEjecutar) {
            //Llamar el siguiente menú en la lista
            if (posicionMostrandose < menus.size() - 1) {
                CardLayout cd = (CardLayout) opciones.getLayout();
                cd.show(opciones, menus.get(++posicionMostrandose).getName());
            } //Si se ha llegado al final de la lista, notificar final de ejecución
            else {
                terminar();
            }
        }
    }//GEN-LAST:event_botonOKActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        if (posicionMostrandose > 0) {
            CardLayout cd = (CardLayout) opciones.getLayout();
            cd.show(opciones, menus.get(--posicionMostrandose).getName());
        }
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton botonAtras;
    protected javax.swing.JButton botonOK;
    protected javax.swing.JPanel botonesDeControl;
    protected piezazgraficas.CartaGrafica cartaGrafica1;
    protected javax.swing.JLabel imagenInicio;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel opciones;
    // End of variables declaration//GEN-END:variables

    private void ajustarMarco() {
        cartaGrafica1.setImagenDir(new File(marco));
        cartaGrafica1.ajustar();
        this.getRootPane().setDefaultButton(botonOK);
    }

    public void agregarMenu(PanelDeMenu componente) {
        componente.setName("Menú + " + menus.size());

        //Registrar éste como el invocador del panel
        componente.padre = this;
        //Agregar al arreglo de menús
        menus.add(componente);
        //Agregar al frame principal
        opciones.add(componente, componente.getName());
    }

    public void quitarMenu(PanelDeMenu componente) {
        //Eliminar padre
        componente.padre = null;
        //Eliminar del arreglo
        menus.remove(componente);
        //Eliminar del frame principal
        opciones.remove(componente);
    }

    public synchronized void ejecutar() throws InterruptedException {
        setVisible(true);
        if (terminado) {
            terminado = false;
            botonOK.doClick();
        }
        while (!terminado) {
            wait();
        }
    }

    private synchronized void terminar() {
        notifyAll();
        terminado = true;
    }

    public JButton getBotonAtras() {
        return botonAtras;
    }

    
}
