package Menu;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Ulises Tovar
 */
public class SalaVentana extends PanelDeMenu {


    /**
     * Creates new form Sala
     */
    public SalaVentana() {
        initComponents();
        ajustarOcultajeBotones();
        panelServidor.setVisible(false);
    }

    public JButton getBotonIniciar() {
        return botonIniciar;
    }

    public JButton getBotonSalir() {
        return botonSalir;
    }

    public JTextField getField_rondas() {
        return field_rondas;
    }

    public JPanel getPanelChat() {
        return panelChat;
    }

    public JPanel getPanelConectados() {
        return panelConectados;
    }

    public JPanel getPanelServidor() {
        return panelServidor;
    }

    public JTextField getField_rapidez() {
        return field_rapidez;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelConectados = new javax.swing.JPanel();
        panelChat = new javax.swing.JPanel();
        panelServidor = new javax.swing.JPanel();
        botonIniciar = new javax.swing.JButton();
        label_rondas = new javax.swing.JLabel();
        field_rondas = new javax.swing.JTextField();
        field_rapidez = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        panelConectados.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Jugadores conectados"), javax.swing.BorderFactory.createEtchedBorder()));
        panelConectados.setLayout(new javax.swing.BoxLayout(panelConectados, javax.swing.BoxLayout.Y_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panelConectados, gridBagConstraints);

        panelChat.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Chat grupal"), javax.swing.BorderFactory.createEtchedBorder()));

        javax.swing.GroupLayout panelChatLayout = new javax.swing.GroupLayout(panelChat);
        panelChat.setLayout(panelChatLayout);
        panelChatLayout.setHorizontalGroup(
            panelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelChatLayout.setVerticalGroup(
            panelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panelChat, gridBagConstraints);

        panelServidor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelServidor.setToolTipText("");
        panelServidor.setLayout(new java.awt.GridBagLayout());

        botonIniciar.setBackground(new java.awt.Color(255, 204, 0));
        botonIniciar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panelServidor.add(botonIniciar, gridBagConstraints);

        label_rondas.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        label_rondas.setText("Rondas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelServidor.add(label_rondas, gridBagConstraints);

        field_rondas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.weightx = 1.0;
        panelServidor.add(field_rondas, gridBagConstraints);

        field_rapidez.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.weightx = 1.0;
        panelServidor.add(field_rapidez, gridBagConstraints);

        jLabel1.setText("Segundos gritón:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelServidor.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        add(panelServidor, gridBagConstraints);

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setToolTipText("Salir de la sala");
        botonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(botonSalir, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        padre.botonAtras.doClick();
    }//GEN-LAST:event_botonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField field_rapidez;
    private javax.swing.JTextField field_rondas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_rondas;
    private javax.swing.JPanel panelChat;
    private javax.swing.JPanel panelConectados;
    private javax.swing.JPanel panelServidor;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean ejecutar() {
        return true;
    }

    private void ajustarOcultajeBotones() {
        //Cuando este menú se muestre, el botón OK se ocultará.
        //Cuando este menú se oculte, el botón OK se mostrará.
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent ce) {
                padre.botonOK.setVisible(false);
                padre.botonAtras.setVisible(false);
            }

            @Override
            public void componentHidden(ComponentEvent ce) {
                padre.botonOK.setVisible(true);
                padre.botonAtras.setVisible(true);
            }
        });
    }
    
    /**
     * Ya que esta ventana debería estar siendo usada por un invocador
     * (MenuInicio), utiliza este método para que el menú avance.
     */
    public void avanzar() {
        padre.botonOK.doClick();
    }
}
