/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import conectividad.ClienteGrafico;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ulises Tovar
 */
public class UnirseASala extends PanelDeMenu {

    private final ClienteGrafico cliente;

    /**
     * Creates new form UnirseASala
     *
     * @param cliente el cliente que se intenta conectar
     */
    public UnirseASala(ClienteGrafico cliente) {
        initComponents();
        this.cliente = cliente;
        ajustarBotonConectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        field_ip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        field_puerto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Dirección IP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(field_ip, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Puerto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(field_puerto, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("Ingresa la información de la sala");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(jLabel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_ip;
    private javax.swing.JTextField field_puerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean ejecutar() {
        //Validar el puerto ingresado
        String numero = field_puerto.getText();
        try {
            int puerto = Integer.parseInt(numero);
            //Obtener IP y, finalmente, conectar
            String ip = field_ip.getText();
            cliente.conectar(ip, puerto);
            //Agregar la ventana del cliente como el siguiente menú
            padre.agregarMenu(cliente.getVentana());
            return true;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Puerto inválido");
            return false;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No fue posible conectarse");
            return false;
        }
    }

    private Color botonOK_colorOriginal;
    private String textoOriginal;

    private void ajustarBotonConectar() {
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent ce) {
                //Regresar a su estado original
                if (botonOK_colorOriginal != null) {
                    padre.botonOK.setBackground(botonOK_colorOriginal);
                }
                if (textoOriginal != null) {
                    padre.botonOK.setText(textoOriginal);
                }
            }

            @Override
            public void componentShown(ComponentEvent ce) {
                //Guardar estado original
                botonOK_colorOriginal = padre.botonOK.getBackground();
                textoOriginal = padre.botonOK.getText();
                //Modificar
                padre.botonOK.setText("Conectar");
                padre.botonOK.setBackground(Color.green);
            }

        });
    }
}
